export default [
  {
    id: 1,
    path: "/assets/profiles/akku.jpg",
    rating: "5.0",
    count: "10",
    location: "Hyderabad",
    desc: "Photography with Aakanksha",
    price: "100",
    openSpots: 0,
  },
  {
    id: 2,
    path: "/assets/profiles/sri.jpg",
    rating: "4.8",
    count: "9",
    location: "Online",
    desc: "Web Dev classes with Srinivas Mekala",
    price: "98",
    openSpots: 20,
  },
  {
    id: 3,
    path: "/assets/profiles/badminton.jpg",
    rating: "4.8",
    count: "9",
    location: "Hyderabad",
    desc: "Learn Badminton and stay fit",
    price: "60",
    openSpots: 20,
  },
  {
    id: 4,
    path: "/assets/profiles/designer.jpg",
    rating: "4.2",
    count: "9",
    location: "Online",
    desc: "Bring your imaginations to reality with professional designers",
    price: "75",
    openSpots: 8,
  },
  {
    id: 5,
    path: "/assets/profiles/guitarist.jpg",
    rating: "3.9",
    count: "9",
    location: "Italy",
    desc: "Listen to the world with music",
    price: "102",
    openSpots: 3,
  },
  {
    id: 6,
    path: "/assets/profiles/gym-trainer.jpg",
    rating: "4.1",
    count: "9",
    location: "New York",
    desc: "Stay fit and Build muscle. Train with our professional trainers",
    price: "50",
    openSpots: 15,
  },
  {
    id: 7,
    path: "/assets/profiles/parkour.jpg",
    rating: "4.2",
    count: "9",
    location: "Germay",
    desc: "Bring the primate within you, learn Parkout",
    price: "80",
    openSpots: 2,
  },
  {
    id: 8,
    path: "/assets/profiles/skater.jpg",
    rating: "3.5",
    count: "9",
    location: "Moscow",
    desc: "Run with wheels and feel the speed",
    price: "65",
    openSpots: 0,
  },
  {
    id: 9,
    path: "/assets/profiles/akachi.jpg",
    rating: "4.7",
    count: "9",
    location: "Online",
    desc: "Life lessons from Akachi Mowa",
    price: "85",
    openSpots: 15,
  },
];
