export default [
  {
    id: 1,
    path: "/assets/profiles/akku.jpg",
    rating: "5.0",
    count: "10",
    location: "online",
    desc: "Photography with Aakanksha",
    price: "100",
    openSpots: 2,
  },
  {
    id: 2,
    path: "/assets/profiles/sri.jpg",
    rating: "4.8",
    count: "9",
    location: "India",
    desc: "Web Dev classes with Srinivas Mekala",
    price: "98",
    openSpots: 0,
  },
  {
    id: 3,
    path: "/assets/profiles/sri.jpg",
    rating: "4.8",
    count: "9",
    location: "India",
    desc: "Web Dev classes with Srinivas Mekala",
    price: "98",
    openSpots: 0,
  },
  {
    id: 4,
    path: "/assets/profiles/sri.jpg",
    rating: "4.8",
    count: "9",
    location: "India",
    desc: "Web Dev classes with Srinivas Mekala",
    price: "98",
    openSpots: 0,
  },
  {
    id: 5,
    path: "/assets/profiles/sri.jpg",
    rating: "4.8",
    count: "9",
    location: "India",
    desc: "Web Dev classes with Srinivas Mekala",
    price: "98",
    openSpots: 0,
  },
  {
    id: 6,
    path: "/assets/profiles/sri.jpg",
    rating: "4.8",
    count: "9",
    location: "India",
    desc: "Web Dev classes with Srinivas Mekala",
    price: "98",
    openSpots: 0,
  },
  {
    id: 7,
    path: "/assets/profiles/sri.jpg",
    rating: "4.8",
    count: "9",
    location: "India",
    desc: "Web Dev classes with Srinivas Mekala",
    price: "98",
    openSpots: 0,
  },
  {
    id: 8,
    path: "/assets/profiles/sri.jpg",
    rating: "4.8",
    count: "9",
    location: "India",
    desc: "Web Dev classes with Srinivas Mekala",
    price: "98",
    openSpots: 0,
  },
  {
    id: 9,
    path: "/assets/profiles/sri.jpg",
    rating: "4.8",
    count: "9",
    location: "India",
    desc: "Web Dev classes with Srinivas Mekala",
    price: "98",
    openSpots: 0,
  },
  {
    id: 10,
    path: "/assets/profiles/sri.jpg",
    rating: "4.8",
    count: "9",
    location: "India",
    desc: "Web Dev classes with Srinivas Mekala",
    price: "98",
    openSpots: 0,
  },
  {
    id: 11,
    path: "/assets/profiles/sri.jpg",
    rating: "4.8",
    count: "9",
    location: "India",
    desc: "Web Dev classes with Srinivas Mekala",
    price: "98",
    openSpots: 0,
  },
  {
    id: 12,
    path: "/assets/profiles/sri.jpg",
    rating: "4.8",
    count: "9",
    location: "India",
    desc: "Web Dev classes with Srinivas Mekala",
    price: "98",
    openSpots: 0,
  },
  {
    id: 13,
    path: "/assets/profiles/sri.jpg",
    rating: "4.8",
    count: "9",
    location: "India",
    desc: "Web Dev classes with Srinivas Mekala",
    price: "98",
    openSpots: 0,
  },
  {
    id: 14,
    path: "/assets/profiles/sri.jpg",
    rating: "4.8",
    count: "9",
    location: "India",
    desc: "Web Dev classes with Srinivas Mekala",
    price: "98",
    openSpots: 0,
  },
  {
    id: 15,
    path: "/assets/profiles/sri.jpg",
    rating: "4.8",
    count: "9",
    location: "India",
    desc: "Web Dev classes with Srinivas Mekala",
    price: "98",
    openSpots: 0,
  },
  {
    id: 16,
    path: "/assets/profiles/sri.jpg",
    rating: "4.8",
    count: "9",
    location: "India",
    desc: "Web Dev classes with Srinivas Mekala",
    price: "98",
    openSpots: 0,
  },
  {
    id: 17,
    path: "/assets/profiles/sri.jpg",
    rating: "4.8",
    count: "9",
    location: "India",
    desc: "Web Dev classes with Srinivas Mekala",
    price: "98",
    openSpots: 0,
  },
  {
    id: 18,
    path: "/assets/profiles/akachi.jpg",
    rating: "4.4",
    count: "6",
    location: "Kenya",
    desc: "Life Lessons with Akachi Mowaa",
    price: "120",
    openSpots: 0,
  },
  {
    id: 19,
    path: "/assets/profiles/akachi.jpg",
    rating: "4.4",
    count: "6",
    location: "Kenya",
    desc: "Life Lessons with Akachi Mowaa",
    price: "120",
    openSpots: 0,
  },
  {
    id: 20,
    path: "/assets/profiles/akachi.jpg",
    rating: "4.4",
    count: "6",
    location: "Kenya",
    desc: "Life Lessons with Akachi Mowaa",
    price: "120",
    openSpots: 0,
  },
  {
    id: 21,
    path: "/assets/profiles/akachi.jpg",
    rating: "4.4",
    count: "6",
    location: "Kenya",
    desc: "Life Lessons with Akachi Mowaa",
    price: "120",
    openSpots: 0,
  },
  {
    id: 22,
    path: "/assets/profiles/akachi.jpg",
    rating: "4.4",
    count: "6",
    location: "Kenya",
    desc: "Life Lessons with Akachi Mowaa",
    price: "120",
    openSpots: 0,
  },
  {
    id: 23,
    path: "/assets/profiles/akachi.jpg",
    rating: "4.4",
    count: "6",
    location: "Kenya",
    desc: "Life Lessons with Akachi Mowaa",
    price: "120",
    openSpots: 0,
  },
  {
    id: 24,
    path: "/assets/profiles/akachi.jpg",
    rating: "4.4",
    count: "6",
    location: "Kenya",
    desc: "Life Lessons with Akachi Mowaa",
    price: "120",
    openSpots: 0,
  },
];
