export default [
  {
    id: 1,
    path: "/assets/profiles/akku.jpg",
    rating: "5.0",
    count: "10",
    country: "online",
    desc: "Photography with Aakanksha",
    price: "100",
    openSpots: 2,
  },
  {
    id: 2,
    path: "/assets/profiles/sri.jpg",
    rating: "4.8",
    count: "9",
    country: "India",
    desc: "Web Dev classes with Srinivas Mekala",
    price: "98",
    openSpots: 0,
  },
  {
    id: 2,
    path: "/assets/profiles/sri.jpg",
    rating: "4.8",
    count: "9",
    country: "India",
    desc: "Web Dev classes with Srinivas Mekala",
    price: "98",
    openSpots: 0,
  },
  {
    id: 2,
    path: "/assets/profiles/sri.jpg",
    rating: "4.8",
    count: "9",
    country: "India",
    desc: "Web Dev classes with Srinivas Mekala",
    price: "98",
    openSpots: 0,
  },
  {
    id: 2,
    path: "/assets/profiles/sri.jpg",
    rating: "4.8",
    count: "9",
    country: "India",
    desc: "Web Dev classes with Srinivas Mekala",
    price: "98",
    openSpots: 0,
  },
  {
    id: 2,
    path: "/assets/profiles/sri.jpg",
    rating: "4.8",
    count: "9",
    country: "India",
    desc: "Web Dev classes with Srinivas Mekala",
    price: "98",
    openSpots: 0,
  },
  {
    id: 2,
    path: "/assets/profiles/sri.jpg",
    rating: "4.8",
    count: "9",
    country: "India",
    desc: "Web Dev classes with Srinivas Mekala",
    price: "98",
    openSpots: 0,
  },
  {
    id: 2,
    path: "/assets/profiles/sri.jpg",
    rating: "4.8",
    count: "9",
    country: "India",
    desc: "Web Dev classes with Srinivas Mekala",
    price: "98",
    openSpots: 0,
  },
  {
    id: 2,
    path: "/assets/profiles/sri.jpg",
    rating: "4.8",
    count: "9",
    country: "India",
    desc: "Web Dev classes with Srinivas Mekala",
    price: "98",
    openSpots: 0,
  },
  {
    id: 2,
    path: "/assets/profiles/sri.jpg",
    rating: "4.8",
    count: "9",
    country: "India",
    desc: "Web Dev classes with Srinivas Mekala",
    price: "98",
    openSpots: 0,
  },
  {
    id: 2,
    path: "/assets/profiles/sri.jpg",
    rating: "4.8",
    count: "9",
    country: "India",
    desc: "Web Dev classes with Srinivas Mekala",
    price: "98",
    openSpots: 0,
  },
  {
    id: 2,
    path: "/assets/profiles/sri.jpg",
    rating: "4.8",
    count: "9",
    country: "India",
    desc: "Web Dev classes with Srinivas Mekala",
    price: "98",
    openSpots: 0,
  },
  {
    id: 2,
    path: "/assets/profiles/sri.jpg",
    rating: "4.8",
    count: "9",
    country: "India",
    desc: "Web Dev classes with Srinivas Mekala",
    price: "98",
    openSpots: 0,
  },
  {
    id: 2,
    path: "/assets/profiles/sri.jpg",
    rating: "4.8",
    count: "9",
    country: "India",
    desc: "Web Dev classes with Srinivas Mekala",
    price: "98",
    openSpots: 0,
  },
  {
    id: 2,
    path: "/assets/profiles/sri.jpg",
    rating: "4.8",
    count: "9",
    country: "India",
    desc: "Web Dev classes with Srinivas Mekala",
    price: "98",
    openSpots: 0,
  },
  {
    id: 2,
    path: "/assets/profiles/sri.jpg",
    rating: "4.8",
    count: "9",
    country: "India",
    desc: "Web Dev classes with Srinivas Mekala",
    price: "98",
    openSpots: 0,
  },
  {
    id: 2,
    path: "/assets/profiles/sri.jpg",
    rating: "4.8",
    count: "9",
    country: "India",
    desc: "Web Dev classes with Srinivas Mekala",
    price: "98",
    openSpots: 0,
  },
  {
    id: 3,
    path: "/assets/profiles/akachi.jpg",
    rating: "4.4",
    count: "6",
    country: "Kenya",
    desc: "Life Lessons with Akachi Mowaa",
    price: "120",
    openSpots: 0,
  },
  {
    id: 3,
    path: "/assets/profiles/akachi.jpg",
    rating: "4.4",
    count: "6",
    country: "Kenya",
    desc: "Life Lessons with Akachi Mowaa",
    price: "120",
    openSpots: 0,
  },
  {
    id: 3,
    path: "/assets/profiles/akachi.jpg",
    rating: "4.4",
    count: "6",
    country: "Kenya",
    desc: "Life Lessons with Akachi Mowaa",
    price: "120",
    openSpots: 0,
  },
  {
    id: 3,
    path: "/assets/profiles/akachi.jpg",
    rating: "4.4",
    count: "6",
    country: "Kenya",
    desc: "Life Lessons with Akachi Mowaa",
    price: "120",
    openSpots: 0,
  },
  {
    id: 3,
    path: "/assets/profiles/akachi.jpg",
    rating: "4.4",
    count: "6",
    country: "Kenya",
    desc: "Life Lessons with Akachi Mowaa",
    price: "120",
    openSpots: 0,
  },
  {
    id: 3,
    path: "/assets/profiles/akachi.jpg",
    rating: "4.4",
    count: "6",
    country: "Kenya",
    desc: "Life Lessons with Akachi Mowaa",
    price: "120",
    openSpots: 0,
  },
  {
    id: 3,
    path: "/assets/profiles/akachi.jpg",
    rating: "4.4",
    count: "6",
    country: "Kenya",
    desc: "Life Lessons with Akachi Mowaa",
    price: "120",
    openSpots: 0,
  },
];
